[development]
port = 3000
workers = 8

[development.databases]
 postgres = { url = "postgres://addempsea:123456789@4.tcp.ngrok.io:10688/rustly-notes" }

[production]

[production.databases]
postgres = { url = "postgres://addempsea:123456789@8.tcp.ngrok.io:11724/rustly-notes" }
